// <auto-generated />
namespace DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class ChangedLatLongToAllowNull : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206221743400_ChangedLatLongToAllowNull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1dzXLbOBK+b9W+g0r3WI7jzHhS8kzZsj3rWjvxRp65wyQssUISHBJyWc+2h32kfYUB+AuQDRIASUtOfEmZIPsD0A1046f15f///d/8t+fAnzzhOPFIeDp9f3A4neDQIa4Xrk6nG/r47mT626///Mf80g2eJ38W333g3zHJMDmdrimNPs1mibPGAUoOAs+JSUIe6YFDghlyyezo8PCX2fv3M8wgpgxrMpl/3YTUC3D6wB4XJHRwRDfIvyUu9pO8nL1ZpqiTzyjASYQcfDq9QBSdOQ5OkunkzPcQa8ES+4/TSXT86Y8EL2lMwtUyQtRD/v02wuz9I/ITnLf3U3Ss2+TDI97kGQpDQhkcCa26PC07w7pzybpNt7xZaZdOp2f+w0b6hH30b7yVCljRXUwiHNPtV/woCl6708lMFp7VpUvZuiBvxen0OqQfjqaTzxvfRw8+LpXFtLmkJMa/4xDHiGL3DlGKY2b7axenvWhUXavo3qM+LqphZmEjajq58p6xe4PDFV2XVd2i56Lk/U9sXP0RemwAMiEabzDQtPZqz2LqJbS7gyLKfFYZpt1cKbiVvcpmGRtMs0P9Lcb/NTXYUZvBsmcrTS82CSUBjm10XcjaaFuUHVvfV16cUAulH/eeJDfIquJWY2tVvCBBhMKtYb0nZoMMmEOuG6cRw6jan/tWu0gHwXC21alzyWLVoANKq6OEBfT4xft6RxKK/AWTN3VbvWtek9B49hz3rPQKPb90lZcB8nzDSvvH8AvsY+ZQi3rPCfExCo1hlpsoIjH9iqMWb66jhd8xuSFOAcGeVjGK1ltTmBu2MvXoRhitTJ2+sU1u2GLUFEU77l4GkU+2GNvE3ULWJu6KsmPH3Z1FP9uA379mm8X4h75Okk08Nv2Se9Jr8p17MV1fCEGN/33vBcbN+ZcX4yFw3hYTb4uJt8XEPiwmesQ5Fj1iqyCXCtpEuFLwR9rGX4dPxHOsFJ2L2qhaEB1b"
                       + "2frnBe04eZO74pMW1rnn+8zqO4pTee27CFd51TuJWkW3dxO88tp3F8PuCau4HLnY8QL+eBezv/KrhZPpZOkgjjfYcWw+aW68sI+H4eI9vEwhPran0XZqHYaKkfOtLwgbKvQu5o59GIs3a/jPBuVaGeEY/xa7HuLPNqOmFLYZM5Lwj7QQuPPR1re8OylkbRQuyv6I+k6n+7BKBz8v3couDPQ53T8N4vdMKtE2hrURrLXau7cjjvmjw/6XvB2X2DorFgNX3HU63L6x0zvzCCKS4NhUlYbuA9ACXzgm2CGhm/RTw/mWYjWETluGXlXoH3o/scFudeLNBa2OuwvBsednWtEFTpzYi7IcFrMB9nGAI8SYDrKtvQzdQXDOfP8ClQtLvcul9qG0ICFFbBsQF7N57YWEfOPF+Lk+sDKRJaaiL2MTp6ogy2g6yHKD6p1piKfpIaB8lqzSBVCcYEAQZRZGF0hxfQOBlFdKXSCpI4UQssO6LvF8gwQBFMdQmhB8S9cCk+43u6DK8AIBVRuQLphieQShlGtqXZB0VdCGlC1UuuCUMHriqUsCB0rqhsF5V86w8t18luUG5gXzmSKJcH6Looi5OiGpMC+ZLLOMwsW7pXlmX5BhzJwESPArW1vWxJw4WuHaWx72XZxeCvKsxgfEvc7CDZqfafmTojLJrdRjWKX04nP+d37tXqZWHgB5iaLqrlhvAmastGO4bAGYz5hL8piNYtU6bkH8TRC2pja24eTXmyJKXqSPUeXZSY1R5O1lY66mjrqyZw1t15YJddvpWTb3+LamBXIY9WyrEBxOoSqkbJMhomQle2OSKoZaGgVOd9Qyi1pUpU7xzkJUqjpvsg1NSGoQwYRifawqM0OEqkr1kcpEQ6mDRaGBVyguUaQxXBQatCddq0uNAVbvbQj5rYYIkReZaCW/nZC1khfq44j3DCKUWG6Alt1/S0Br4EindRTy62xp/PECffn8blpEyIv0Mcq0NRGlLDSwtJS3"
                       + "JhlceqOPWCSwiVhFmcHsrPLXpOlZFZvMdApBlaV749qrnY2la4cz6lKELteuFlUP4yqNTh7LqtS8diMN5Y6HDBJDLPaE1DQRRyjWxxIS1EQsoVgfq8pRE6Gq0rfA9Ra47APXjlxofq5j6T+BTK1UvMt5KuTUITI/xZdjJJjs1Yaz93uV8pjM0h5gSpeWRZSSKl0KKQ+iQpWZYW1Yw256pHQtoG2m3rqesiUHEvmdMWrThUsvjPEAhy6/MW8h5N7r74xRVc4eeG2w+sgSnaTVR1a0bzM8O8XuN8ubqVUpiOZMh6U75lSRTwXMKjhTSwNzEA9S3qlLtodv6NtwhGtOEUko1seq0qREqKp0b8akcB1iOSIVSVspRNd4bJFVaVZKDxCV25L/1Ya39+uC6qbJ0kBwipeWfdSiyqW3kDYkrb9b0pa+A+PkV289LQTkIxmZSSH/MrYydcM7slg/S9layNAyQ4U0/fkz9k3g0G57qG1hleBVv5DISg16KGVsSV2U3hgsl7PMLWmJnBWNu6jZ1Yluln9ge5zbzBVLxTvPcmE55bFOkSAmHezA6WadOFL+VwNQemt0rFckdtWO9opig1YWqV1S44pCEy+SpXbJTiQre+Hx18hcqX9S1p6XlM9l5kqeNdLNidVII8k+4XmT5MlzeQrJcptQHBzwDw6Wf/kL30tzbYoPblHoPWIW2ck3HKYpuic1ei0L6qtZkrj+nvNfeVwLnTmWfX5tHz6h2FmjuEl01ZPZKm3698NrNYolsmVImyGODgf6xcX+MFaNoskGdwWozmPzYV1n4wBxj8xxa1RTIOxJh/GBUSv/qBZE/dkYVfyxrIZejakbBsKs/bh1INTmj1bhmWoOLPIqwMPquAdtwkCIEisCiGkRK2oMSg9eV6gABhDAnlQLOebcSavBuJNizM/c+zEndWO8Qt6kUbz/WE5aL6pYAHcvwT4Y+5MGn5HFdGiwGbnsbzoAm5EtzltAewtouw1or5nF"
                       + "57VvWvaEn2cUNSo2Rv2JeSBX24OYZyCXC/DuDOTPIFqdYaHH8cNKUpyB3LHEeeP+uJw3o8xe2Ef0I7uxgWj8KL2noZs11KluBjzX2yuim9ceK/eHwuZ70eQrJKd5ES/0eohldjMSUwaZfpQxFlt3lUvrRxdj0ZA6WQyso67ZCnQQ4IKx6aHEBGPRv6FD7uvhgRllOqkoYOBh89HmYEZmeLHeH9UYXqxxZIaX7sNvQ3aXBmmD3JgyKUC641byu2R39ay3D/xcMWujCfVLC/MLCG3GCtNKCgPhG1PGtDLGQDWY8cmo6WQgbCOmmTaiGQjcgoWmi4SmpRozlpp2khqoGnMOm1YKG6gKO4Kbbn6btroMKHDUDDhQBQbkOGpuHHA+5Hw6kEfT4M1pZhnNZ+L/zzdnocNbVRD8f+sLscMjSQVafHMdPpLCGbNOiS0qPmmsqihyeXod80uPyGGBn/A8u5Sc7E/kb9IJ/4Dd6/DLhkYbepYkOHjwpYSu+ay9/pQcSG7z/EsaC5MhusCa6fFY9SU833i+W7b7Cog0CggeU/KQz1q1pDz0r7YlEsA9qQDK1XeBIxzyBcM9Zt6SgSVfwiV6wuq2detQ1tj8wkOrGAVJjlHJs0c2/Nzg+de/AZB1OFJhcgAA"; }
        }
    }
}
