// <auto-generated />
namespace DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class test : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206212019262_test"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1dzVLkNhC+pyrvMDX3YJYlCdkakoIBEirLLtkhuQtbgGtty7E1FPNsOeSR8gqR5D/JlmRJtplhl8sWo3F/LXVL3bLU8+1///y7+OUpjmaPMMtDlBzP3+ztz2cw8VEQJvfH8zW+++5o/svP336zOA/ip9lf1XNv6XNEMsmP5w8Yp+88L/cfYAzyvTj0M5SjO7zno9gDAfIO9vd/8t688SCBmBOs2WzxaZ3gMIbsA/m4RIkPU7wG0RUKYJSX7eSbFUOdfQAxzFPgw+P5GcDgxPdhns9nJ1EISA9WMLqbz9LDd3/mcIUzlNyvUoBDEN1sUki+vwNRDsv+vksPTbu8f0C77IEkQZjAocRpyPN6MGQ452TYeEO7xYZ0PD+JbtfCI+Sh3+FGaCBN1xlKYYY3n+AdL3gZzGeeKOy1pWvZtiDtxfH8MsFvD+azD+soArcRrI1FrLnCKIO/wgRmAMPgGmAMM+L7ywCyUXRUtxTdhDiClRriFjKj5rOL8AkG72Fyjx9qVVfgqWp58wOZV38mIZmARAhnayjpml7tSYbDHPcPkEdZeI1j9O5i4E7+qrtl7TDDAQ33GP3X1mEHOocVn50svVznGMUwc7F1JetibV52antfhFmOHYx+OHiRvAdOirXONlK8RHEKko2l3iO7SSZZQ0GQsYxhpfbHoWqXbBKM51sTnSuSq0adUEYDRSShZ88+1muUYxAtibxt2Bqs+QEl1qvncKDSC/D03CrPYxBGlkqH5/AzGEESUCu9pwhFECTWMKt1mqIMf4KpJpoPyFHncRqhDYQuOaqSdclRvOzUOWprmcI1OQ7X7LJxfTs0oJBJSqZqfoMsJmoX5TTM8MMZlwDo3zdhbN2d38IMjoHzmnhfE+9r4t2FxDsgz5HskTklOSbokuFqwa/plfcyeUSh72ToUtTF1Jzo1MY2f7fW45Rd7stPRlinYRQRr28pT5Xat5GuStVbyVrVsLeTvErt28th"
                       + "N4gormcu9MOYfrzOyF/lMfzRfLbyAcUb7eiyXDTvw2RIhKHiA6JMJT51pDEOaj2OyoD/eSgImSr4OqOBfRyPdzX8sQalVSY48r6CQQjoZ5dZUwu7zBlB+GvaCFxHYBM53jNUsi4G52W/Rnuz5T6u0aWP12FlGw76wN6fRol7NkqMneHsBGerDh7thHP+YH/4hWjPha/JjsUiFOuB+l7szM484hTlMLM1pWX4kFiBbhxz6KMkyIeZ4XSDoRrCpC9j7yrMD70fyWR3OvGmgk7H3ZXg1OuTKTqDuZ+FaVHvYTfBvh/hCDHDo7zWnifBKDgnUXQG6o2l2UWMfiotUYIBeQ3IqtX8ECYIfabN8Kk9sQqRFcR8LCMLp1FQVP/sFXU07cF0xFkphVS+KOzoA6hOMGQQdcVCH0h1fSMDqa+U+kBYIJUhFId1feLlC5IMoDqGMoSgr3QaGPa+2QdVpxcZUPMC0gdTbY9kKPWe2hSE7Qp0SMVGpQ9OCWMmzkKSdKKwMCxdd/UKq79beEUdXdmw8BQFd4srkKYk1HEFeGXLbFVU3y2/W9lXwcUFhufnkmK4ure1JhLEwT1sfUvTfgDZpSCtALwFNOosg7j7mFE8qZQJYaWdwxqjV4/Tv8sr6roMcU9Sw8eb7oKMJibOYgODdQ+ktX+lJM3ZIFPt45YoWseJtgxQh1Neb/IoZZM5RlOTJnRGUeNWzLmWOdrG9jrWbm0T2r4z82wZ8V1dK6n3M/OtQnA8g6qQipcMHqVo2RmXNDnU0Sny0kAjt6hFVebk7yx4o6prDHVoXFEDD8Y1m2M1lRk8VNNqjlQX5QkDrBotokJ1iSLM4arRoj9sry50RrJ71yGUtxo8RNlkY5XydkK0StlojsPfM/BQfLsFWnH/LQA9SI50tLOQXmcL8482mMuXd9M8QtlkjlGXePEodaOFp4UaL8Hhwjc7E/6a3b9j+JNXnTGEvvCnFlW7uik1E/2tKl/ToY0XssYMpGNs"
                       + "iLjyLR6HazbH4oq4eCyu2RyrqePioZrW1+D+Gtzdg/uWQmh59uEYPyXVTEy8L3gq5FR2rE+6eUsqCqJ0ODu/n6+Pkhz9IS17MvKIUlJlS64sgDeosnpKhzXui4FQ0iTpm220bpc1iYlE/M4atRvChS+s8SQBXfzGvoey8N7+zhpVFewlX1vsPopiIGH3UTTt2govTnqHrfJu+REDMVzpcumeNVXVHElWlbyayQBzlAhS3zsLvpffYutwuKtAHolrNsdqSol4qKZ1Z+Ykd2XgOCMVhU0Mom8+amRVlhWu0HnjamqkdHg7vy9obmMcHSQvgzLyj1pUufXmSmuE/bemtOcLcE55PTXQQ5KaHSs3KeSfx1e2YXhLHhvmKVcPWXpmrJRmvn6mvi0bO2yP9VrYFEG1D+2LVosRClVNwhCFbyy2y0V1k7BFLpqm3dRs60S3uKN3Pc7t1lMx8d6zXLmc8linKqISDnbkJVm9OEKNVAdQ+NbqWK8qfmod7VXNFr2syp+EzlWNNlGkKH8Sg0jR9szzr1Pd0X6k1l621J/r6o6ysqKfY6lTalE8QmsL0WMY0DKL1SbHMN6jD+yt/o6WUcjqUaoHrkAS3kGS2dFnmLAy1qMWXZMDlZKX50G043xKIbVCbx3ikF+kJ48g8x9A1iVOGsiUxLr+5fAkTeKJYhuic8TB/ki/StgdBqRJLNnhd5Ca89B+WrcZK6S4B/a4LeoiKexRj/Mls1b84akU9UdrVP4HpQZ2taY3GAmz9QPQkVC7P+yUr1R7YJ57QD6tDgdQC4yEKDAHSDEdckWLkec27EsVkgkkYeNppZwvgotnkmg5VVAzi8IOwP1blrfW66/DkdM7fboYHYacgPyNR2DIccV5TQCvCWC7CeAlM8O89E3+jnC+TGJGxYvEcLIXWagdQPYyUsiVcLmMFM9kVC3jQk8Th5VEKyOFY4FHJfh6eVQmWb3yGDGMQMUFovND54GO7mpo06eMeA62U+Qp"
                       + "Lz1X7g4typdiyRdIePIsUejlkJVsZyYyVpJhNCQOr+6qkDaMgsShI20CErmN+larZIASfhGXEQrsIg7jGzvlvhxukUmWk4pWRD5tvnc5mBFZQ5zfj1qsIc44ImtI/2GxJWNIhwhA7Ex9iS7cCSs5Q4q7bTLaW3quWPTRhk5EwyYihbZjGtESjcjwrWlItCwkMg12HCVqihIZthV7iY68RAbuwGzSR2yiUWPHfKInPpGpsedF0dKiyFS4kab0c6bodFnQqqhZVWQKLAhX1Hwr0vVQcrTIIpoBF0u3Kmfh8f8/2oKkjvC+gaD/W1oCfZpJGtDqmcvkDlXBmAyK71H1SGdXhUFAy9FIXLoDPkn8iNalMcKrv0C0Zgv+FgaXycc1Ttf4JM9hfBsJBVALT6+fEc6IfV58ZLkwH2MIpJshzVUfk9N1GAV1vy8kmUYBQXNKmfJJr1aYpv77TY0k4TNUAJXmO4MpTOiG4QaSaEnA8o/JCjxCdd/6bShabHEWgvsMxHmJ0ciTj2T6BfHTz/8DubTmdeFvAAA="; }
        }
    }
}
