// <auto-generated />
namespace DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class GeoLocationTableColumns : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206212050472_GeoLocationTableColumns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1dzXLbOBK+b9W+g0r3WI7jzHhS8kzZsj3rWjvxRp65wyQssUISHBJyWc+2h32kfYUB+AuQDRIASUtOfEmZIPsD0A1046f15f///d/8t+fAnzzhOPFIeDp9f3A4neDQIa4Xrk6nG/r47mT626///Mf80g2eJ38W333g3zHJMDmdrimNPs1mibPGAUoOAs+JSUIe6YFDghlyyezo8PCX2fv3M8wgpgxrMpl/3YTUC3D6wB4XJHRwRDfIvyUu9pO8nL1ZpqiTzyjASYQcfDq9QBSdOQ5OkunkzPcQa8ES+4/TSXT86Y8EL2lMwtUyQtRD/v02wuz9I/ITnLf3U3Ss2+TDI97kGQpDQhkcCa26PC07w7pzybpNt7xZaZdOp2f+w0b6hH30b7yVCljRXUwiHNPtV/woCl6708lMFp7VpUvZuiBvxen0OqQfjqaTzxvfRw8+LpXFtLmkJMa/4xDHiGL3DlGKY2b7axenvWhUXavo3qM+LqphZmEjajq58p6xe4PDFV2XVd2i56Lk/U9sXP0RemwAMiEabzDQtPZqz2LqJbS7gyLKfFYZpt1cKbiVvcpmGRtMs0P9Lcb/NTXYUZvBsmcrTS82CSUBjm10XcjaaFuUHVvfV16cUAulH/eeJDfIquJWY2tVvCBBhMKtYb0nZoMMmEOuG6cRw6jan/tWu0gHwXC21alzyWLVoANKq6OEBfT4xft6RxKK/AWTN3VbvWtek9B49hz3rPQKPb90lZcB8nzDSvvH8AvsY+ZQi3rPCfExCo1hlpsoIjH9iqMWb66jhd8xuSFOAcGeVjGK1ltTmBu2MvXoRhitTJ2+jfem5jDakfcyiHyyxdgm8hayNpFXlB078u4s/tmG/P412yzHP/R1k2zqsQmY3JNe0+/ci+n6Qghr/O97LzBuzr+8GA+B87aceFtOvC0n9mE50WOHyaJHbBXkUkGbCFcK/kgb+evwiXiOlaJzURtVC6JjK1v/"
                       + "xKAdJ29yV3zSwjr3fJ9ZfUdxKq99F+Eqr3onUavo9m6CV1777mLYPWEVlyMXO17AH+9i9ld+uXAynSwdxPEGO5DNJ82NF/bxMFy8h5cpxMf2NNpOrcNQMXK+9QVhQ4XexdyxD2PxZg3/2aBcKyMc5N9i10P82WbUlMI2Y0YS/pEWAnc+2vqWtyeFrI3CRdkfUd/pdB9W6eDnpVvZhYE+p/unQfyeSSXaxrA2grVWe/d2xDF/dNj/mrfjGltnxWLgirvOh9s3dnpnHkFEEhybqtLQfQBa4AvHBDskdJN+ajjfUqyG0GnL0KsK/UPvJzbYrU68uaDVcXchOPb8TCu6wIkTe1GWxWI2wD4OcIQY00G2tZehOwjOme9foHJhqXe91D6UFiSkiG0D4mI2r72QkG+8GD/XB1YmssRU9GVs4lQVZDlNB1l2UL0zDfE0QQSUz9JVugCKEwwIoszD6AIprm8gkPJKqQskdaQQQnZY1yWeb5AggOIYShOCb+laYNL9ZhdUGV4goGoD0gVTLI8glHJNrQuSrgrakLKFShecEkZPPHVJ4EBJ3TA478oZVr6bz7LswLxgPlOkEc5vURQxVyekFeYlk2WWU7h4tzTP7QsyjJmTACl+ZWvLmpgTRytce8vDvovTS0Ge1/iAuNdZuEHzMy1/UlQmuZV6DKuUXnzO/84v3svkygMgM1FU3RXrTcCMlXYMly0AMxpzSR6zUaxaxy2IvwnC1uTGNpz8elNEyYv0MapMO6kxisy9bMzV1FFX9qyh7doyoW47PcvmHt/WtEAWo55tFYLDKVSFlG0yRJSsZG9MUsVQS6PACY9aZlGLqtQp3lmISlVnTrahCUkNIphQrI9VZWaIUFWpPlKZaih1sCg08ArFJYo0hotCg/aka3WpMcDqvQ0hv9UQIfIiE63ktxOyVvJCfRzxnkGEEssN0LL7bwloDRzptI5Cfp0tjT9eoC+f302LCHmRPkaZuCailIUGlpYy1ySD"
                       + "S2/0EYsUNhGrKDOYnVUGmzQ9q2KTmU4hqLJ0b1x7tbOxdO1wRl2K0OXa1aLqYVyl0cljWZWa126kodzxkEFiiMWekJom4gjF+lhCgpqIJRTrY1U5aiJUVfoWuN4Cl33g2pELzc91LP0nkKmVinc5T4WcOkTmp/hyjASTvdpw9n6vUh6TWdoDTOnSsohSUqVLIeVBVKgyM6wNa9hNj5SuBbTN1FvXU7bkQCK/M0ZtunDphTEe4NDlN+YthNx7/Z0xqsrZA68NVh9ZopO0+siK9m2GZ6fY/WZ5M7UqBdGc6bB0x5wq8qmAWQVnamlgDuJByjt1yfbwDX0bjnDNKSIJxfpYVZqUCFWV7s2YFK5DLEekImkrhegajy2yKs1K6QGiclvyv9rw9n5dUN00WRoITvHSso9aVLn0FtKGpPV3S9rSd2Cc/Oqtp4WAfCQjMynkX8ZWpm54RxbrZylbCxlaZqiQpj9/xr4JHNptD7UtrBK86hcSWalBD6WMLamL0huD5XKWuSUtkbOicRc1uzrRzfIPbI9zm7liqXjnWS4spzzWKRLEpIMdON2sE0fK/2oASm+NjvWKxK7a0V5RbNDKIrVLalxRaOJFstQu2YlkZS88/hqZK/VPytrzkvK5zFzJs0a6WbEaaSTZJzxvkjx5Lk8hWW4TioMD/sHB8i9/4Xtprk3xwS0KvUfMIjv5hsM0RfekRrBlQX41SxLX33MGLI9roTPHss+v7cMnFDtrFDeprnpyW6VN/36YrUaxRLYMaTPE0eFAv7jYH86qUTTZ4K4A1XlsPqzrbBwg7pE5bo1sCoQ96TA+MGrlH9WCqD8bo4o/ltXQqzF1w0CYtR+3DoTa/NEqPFPNgUVeBXhYHfegTRgIUWJFADEtYkWNQ+nB6woVwAAC+JNqIcecPWk1GHtSjPmZe0/uJA2QV8icNIr/H8tN68UVC+DuRdgHY4/SYDSymBANPiOX/U0H4DOyxXkLaW8hbbch7TXz+Lz2"
                       + "bcueMPSMokbF1qg/NQ/kantQ8wzkcgHmnYH8GUSsMyz0OH5YSYszkDuWWG/cH5f1ZpTZC/uIfnQ3NhCNn6X3NHSzhjrZzYAne3tFdfPaY+X+kNh8L5p8hfQ0L+KFXg+1zG5GYsoh0480xmLrrnJp/QhjLBpSp4uBddQ1W4EOAmwwNj2UuGAs+jd0yH09TDCjTCcVCQw8bD7aHMzIHC/W+6Max4s1jszx0n38bcjv0qBtkBtTpgVIt9xKhpfstp719oGfK2ZtNCF/aeF+AaHNeGFaaWEgfGPSmFbOGKgGM0YZNaEMhG3ENdNGNQOBW/DQdNHQtFRjxlPTTlMDVWPOYtNKYgNVYUdx081w01aXAQmOmgMHqsCAHkfNjgPOh5xRB/JoGsw5zTyj+Uz8P/rmLHR4qwqC/499IXZ4JKlAi2+uw0dSOGPWKbFFxSeNVRVFLk+wY37pETks8BOeaZfSk/2J/E064R+wex1+2dBoQ8+SBAcPvpTSNZ+115/SA8ltnn9JY2EyRBdYMz0eq76E5xvPd8t2XwGRRgHBY0oe8lmrlpSH/tW2RALYJxVAufoucIRDvmC4x8xbMrDkS7hET1jdtm4dyhqbX3hoFaMgyTEqefbIhp8bPP/6N+4QT/BlcgAA"; }
        }
    }
}
